#!/bin/sh /etc/rc.common

START=10
BOOT=0

start() {
	[ -f /etc/uconfig/capabilities.json ] || /usr/libexec/uconfig/capabilities.uc

	mkdir -p /var/run/uci
	uconfig_apply -n /etc/uconfig/configs/uconfig.active
	[ $BOOT -eq 0 ] && reload_config
}

boot() {
	BOOT=1
	start
	/etc/init.d/system start
}

stop() {
	rm -rf /var/run/uci
	reload_config
}
