#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/sbin/uwsd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" --config /etc/uconfig/server.conf
	procd_add_mdns "uconfig" "tcp" "80" "server=1"
	procd_set_param respawn
	procd_close_instance
}
