#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/sbin/uconfig-devices

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 1 0
	procd_close_instance
}
