#!/bin/sh

. /lib/functions.sh

uci commit

SHADOW=/etc/uconfig/shadow
rm -rf $SHADOW
mkdir -p $SHADOW

touch $SHADOW/network $SHADOW/dropbear $SHADOW/dhcpsnoop $SHADOW/ratelimit $SHADOW/ieee8021x $SHADOW/radius $SHADOW/qosify

section_del() {
        uci -c $SHADOW delete $2.$1
}

mkdir -p /var/run/uci
touch /var/run/uci/wireless
wifi config
mv /var/run/uci/wireless $SHADOW/wireless

config_load wireless
config_foreach section_del wifi-iface wireless

uci -c $SHADOW batch <<EOF
set network.globals=globals
set network.globals.ula_prefix=$(uci get network.globals.ula_prefix)
EOF

cat > $SHADOW/dhcp <<EOF
config dnsmasq
	option domainneeded	1
	option boguspriv	1
	option filterwin2k	0
	option localise_queries	1
	option rebind_protection 1
	option rebind_localhost 1

	option local	'/lan/'
	option domain	'lan'
	option expandhosts	1
	option nonegcache	0
	option cachesize	1000
	option authoritative	1
	option readethers	1
	option leasefile	'/tmp/dhcp.leases'
	option resolvfile	'/tmp/resolv.conf.d/resolv.conf.auto'
	option nonwildcard	1
	option localservice	1
	option ednspacket_max	1232
	option filter_aaaa	0
	option filter_a		0
EOF

cat > $SHADOW/firewall <<EOF
config defaults
	option syn_flood    1
	option input        REJECT
	option output       ACCEPT
	option forward      REJECT
	option flow_offloading 1
EOF

uci -c $SHADOW commit

/usr/libexec/uconfig/capabilities.uc

[ -f /usr/bin/pkgen -a ! -f /etc/uconfig/certificates/ca.pem ] && {
	mkdir -p /etc/uconfig/certificates/
	cn=$(cat /etc/board.json  | jsonfilter -e '@.system.label_macaddr')
	[ -z "$cn" ] && cn=$(cat /sys/class/net/eth0/address)
	cn=$(echo $cn | tr -d : | awk '{print tolower($0)}')
	/usr/bin/pkgen -s CN=$cn,O=OpenWrt ca /etc/uconfig/certificates/ca.pem
	/usr/bin/pkgen -s CN=$cn,O=OpenWrt cert /etc/uconfig/certificates/ca.pem /etc/uconfig/certificates/cert.pem
}

uconfig_apply -n /etc/uconfig/uconfig.active

exit 0
